### PR TITLE
Update some modbus salve code and LICENSE file 

### PR DESCRIPTION
**Pull request by armink**
from https://github.com/cwalter-at/freemodbus

### CODE REVIEW

**Comment by pvyleta** [comment]
Perfect, thanks a lot! I really appreciate your effort.

One last thing: If possible, could you change the license for this gitHub repository so that it is clear this code is possible to be used under BSD? I think this would make life much easier to many developers, and also more people would consider your code for their projects.

https://github.com/armink/FreeModbus_Slave-Master-RTT-STM32/blob/master/LICENSE

**Comment by armink** [comment]
The LICENSE file is already changed. Please see 
https://github.com/armink/FreeModbus_Slave-Master-RTT-STM32/pull/42/files#diff-9879d6db96fd29134fc802214163b95aR1

I will also explain the license on the readme.

**Comment by pvyleta** [comment]
OK, I did not realized that. I was using the link on main page of GitHub, and only wanted to ensure it will be changed as well:
image

**Comment by armink** [comment]
when this pr is merge the main page of GitHub will change

**Pull request merged**
